import { Bree_Serif, Courgette, DM_Mono, Rubik } from "next/font/google";
import "./globals.css";

const courgette = Courgette({
  variable: "--font-courgette",
  weight: "400",
  subsets: ["latin"],
});

const breeSerif = Bree_Serif({
  variable: "--font-bree-serif",
  weight: "400",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  weight: ["300", "400", "500"],
  subsets: ["latin"],
});

export const metadata = {
  title: "APT - Central India's Leading CA & CS Institute",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/images/logo.png",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/images/logo-dark.png",
        media: "(prefers-color-scheme: dark)",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${courgette.variable} ${breeSerif.variable} ${rubik.variable} ${dmMono.variable} overflow-x-hidden antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
